spring:
   jpa:
      show-sql: true
   h2:
      console:
         enabled: true
         path: /h2_console
   datasource:
      url: jdbc:h2:mem:testdb
      username: pontep
      password:
      driverClassName: org.h2.Driver

server:  
  port: 9000
# server:
#   port: 9000

# spring:
#   h2:
#     console:
#       enabled: true
#       path: /h2_console

#   datasource:
#     url: jdbc:h2:file:C:/Users/PontepThaweesup/Desktop/sutticketmajor-ticketbooking/database;
#     username: pontep
#     password:
#     driverClassName: org.h2.Driver

#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
# #      ddl-auto: create-drop
#     properties:
#       hibernate.format_sql: true
#       hibernate.generate_statistics: true
#     open-in-view: false